version: '3.3'

services:

  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always

  node:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - db

  nginx:
    build:
      context: ./nginx
      args:
        - WEB_REVERSE_PROXY_PORT=3000
        - WEB_SSL=false
        - SELF_SIGNED=false
        - NO_DEFAULT=false
    volumes:
      - ./data/logs/nginx/:/var/log/nginx
      - ./certbot/certs/:/var/certs
    ports:
      - "8000:80"
      - "443:443"
    tty: true

  react-app:
    container_name: react-app
    build:
      context: ./react-app
      dockerfile: Dockerfile
    volumes:
      - './react-app:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development